name: SAST Pipeline (Semgrep + Bandit)

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:

  semgrep:
    name: Semgrep Scan (Multi-language SAST)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep scan
        run: semgrep scan --config auto --sarif --output semgrep.sarif .

      - name: Upload Semgrep SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif


  bandit:
    name: Bandit Scan (Python SAST)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit scan
        run: bandit -r notification-service/ -f json -o bandit-report.json

      - name: Upload Bandit artifact
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json