name: Trivy Security Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    name: Trivy Scan (FS + Container)
    runs-on: ubuntu-latest

    steps:
      # ─────────────────────────────
      # Checkout code
      # ─────────────────────────────
      - name: Checkout code
        uses: actions/checkout@v4

      # ─────────────────────────────
      # FS scan (dependencies)
      # ─────────────────────────────
      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-fs.sarif
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Upload FS SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif
          category: trivy-fs

      # ─────────────────────────────
      # Docker image scan
      # ─────────────────────────────
      - name: Build image
        run: docker build -t secureshop:test .

      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: secureshop:test
          format: sarif
          output: trivy-image.sarif
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Upload Image SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif
          category: trivy-image